<?php
$this->headScript ()->prependFile ( '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js' );
$this->headLink ()->prependStylesheet ( '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css' );

$escaper = new Zend\Escaper\Escaper ( 'utf-8' );
$_username = $escaper->escapeHtml ( $username );
$_usernameInput = $escaper->escapeHtml ( $inputFieldUsername );
$_updateUserGroupsUrl = $this->url ( 'htgroupmanager/ajax', array( 
		'action' => 'updateUserGroups' 
) );

echo '<select class="groupListing" multiple="multiple" style="width: 300px;">';
$allGroups = $this->htGroupService ()->getGroups ();

// var_dump($allGroups);

foreach ( $allGroups as $group => $users ) {
	$selected = in_array ( $username, $users ) ? 'selected' : '';
	echo "<option value='{$group}' {$selected}>{$group}</option>";
}

echo '</select>';

echo '	<script type="text/javascript">
			var url = "' . $_updateUserGroupsUrl . '";
			$(".groupListing").select2().on("change", function(e){
				$.post(url, {groups : $(this).val(), user : "' . $_username . '"})
					.fail(function(data){
						alert("Es gab einen Übertragungsfehler. Bitte die Seite neu laden!");
					}).done(function(data){
					});
				console.log(e);
});
		</script>';

?>
