<?php
$this->headScript ()->prependFile ( '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js' );
$this->headLink ()->prependStylesheet ( '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css' );

$escaper = new Zend\Escaper\Escaper ( 'utf-8' );
$_username = $escaper->escapeHtml ( $username );
$assignedGroups = $this->htGroupManagerService ()->getGroupsUserIsAssignedTo ( $username );
$manageableGroups = $this->htGroupManagerService ()->getGroupsUserIsAllowedToManage ( $currentUser );

$_updateUserGroupsUrl = $this->url ( 'htgroupmanager/ajax', array( 
		'action' => 'updateUserGroups' 
) );

echo '<select class="groupListing" multiple="multiple" style="width: 300px;">';

foreach ( $manageableGroups as $groupId ) {
	$selected = in_array ( $groupId, $assignedGroups ) ? 'selected' : '';
	echo "<option value='{$groupId}' {$selected}>{$groupId}</option>";
}

echo '</select>';

// TODO: success -> gebe den gespeicherten Wert zurück und zeige ihn an
echo '	<script type="text/javascript">
			var url = "' . $_updateUserGroupsUrl . '";
			$(".groupListing").select2().on("change", function(e){
				var myElem = $(this);
				$.post(url, {groups : $(this).val(), user : "' . $_username . '"}, function(data){
						if(data.msg){
							alert(data.msg);
						}
						
						// $(":selected", myElem).removeProp("selected");
						for(var i in data.data){
							// $("[value=\'" + data.data[i] + "\']").prop("selected");
						}						
					})
					.fail(function(data){
						alert("Es gab einen Übertragungsfehler. Bitte die Seite neu laden!");
					});
				console.log(e);
});
		</script>';

?>
