<?php
$escaper = new Zend\Escaper\Escaper ( 'utf-8' );
$_groupname = $escaper->escapeHtml ( $groupname );
$_usernameInput = $escaper->escapeHtml ( $inputFieldUsername );

?>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<?php
	if (isset ( $messages )) {
		foreach ( $messages as $msg ) {
			$_msg = $escaper->escapeHtml ( $msg );
			echo "<br/><div class='alert alert-success' role='alert'>{$_msg}</div>";
		}
	}
	?>
	
	<div class="panel-heading">Benutzer in der Gruppe '<?php echo $_groupname; ?>'</div>
	<div class="panel-heading"></div>

	<!-- Table -->
	<table class="table table-striped table-bordered table-condensed">
		<thead>
			<tr>
				<th>Benutzer</th>
				<th>Zugehörigkeit löschen</th>
				<th>Zur Benutzeransicht</th>
			</tr>
		</thead>

	
			<?php
			foreach ( $users as $user ) {
				echo '<tr>';
				
				echo "<td>";
				echo $escaper->escapeHtml ( $user );
				echo "</td>";
				
				$url_remove = $this->url ( 'htgroupmanager/user', array (
						'action' => 'removeUser',
						'user' => $user,
						'groupname' => $groupname 
				) );
				echo "<td><a href='{$url_remove}' class='btn btn-default btn-sm'>entfernen</a></td>";
				
				$url_userview = $this->url ( 'htgroupmanager/user', array (
						'action' => 'listGroups',
						'user' => $user 
				) );
				echo "<td><a href='{$url_userview}' class='btn btn-default btn-sm'>zum Benutzer</a></td>";
				
				echo '</tr>';
			}
			?>
			
			<tr>

			<form
				action="<?php echo $this->url('htgroupmanager/user', array('action' => 'add'));?>"
				method="POST">

				<td><input type="text" name="username"
					value="<?php echo $_username; ?>" />
					 <input type="hidden"
					name='groupname' value='<?php echo $_groupname; ?>'/ ></td>
				<td><input type="submit" class='btn btn-default btn-sm' value="neu"></td>
				<td></td>
			</form>
		</tr>

	</table>

</div>
