<?php
$this->headScript ()->prependFile ( '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js' );
$this->headLink ()->prependStylesheet ( '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css' );

$escaper = new Zend\Escaper\Escaper ( 'utf-8' );
$_username = $escaper->escapeHtml ( $username );
$_groupname = $escaper->escapeHtml ( $groupname );

?>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<?php
	if (isset ( $messages )) {
		foreach ( $messages as $msg ) {
			$_msg = $escaper->escapeHtml ( $msg );
			echo "<br/><div class='alert alert-success' role='alert'>{$_msg}</div>";
		}
	}
	?>
	
	<div class="panel-heading">Gruppen des Benutzers '<?php echo $_username; ?>'</div>
	<div class="panel-heading"></div>

	<!-- Table -->
	<table class="table table-striped table-bordered table-condensed">
		<thead>
			<tr>
				<th>Gruppe</th>
				<th>Zugehörigkeit löschen</th>
				<th>Zur Gruppenansicht</th>
			</tr>
		</thead>

	
			<?php
			foreach ( $groups as $group ) {
				echo '<tr>';
				
				echo "<td>";
				echo $escaper->escapeHtml ( $group );
				echo "</td>";
				
				
				$url_remove = $this->url ( 'htgroupmanager/user', array (
						'action' => 'removeGroup',
						'user' => $username,
						'groupname' => $group 
				) );
				echo "<td><a href='{$url_remove}' class='btn btn-default btn-sm' >entfernen</a></td>";
				
				$url_userview = $this->url ( 'htgroupmanager/group', array (
						'action' => 'list',
						'groupname' => $group 
				) );
				echo "<td><a href='{$url_userview}' class='btn btn-default btn-sm'>zur Gruppe</a></td>";
				
				echo '</tr>';
			}
			?>
			
			<tr>

			<form
				action="<?php echo $this->url('htgroupmanager/user', array('action' => 'add'));?>"
				method="POST">

				<td><input type="text" name="groupname"
					value="<?php echo $_groupname; ?>" /> <input type="hidden"
					name='username' value='<?php echo $_username; ?>'/ ></td>
				<td><input type="submit" class='btn btn-default btn-sm' value="neu"></td>
				<td></td>
			</form>
		</tr>

	</table>

</div>
